sudo: true

language: node_js

node_js:
  - "8"
  # nodeは最新版
  # - node

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  # エラー報告
  - set -e
  - npm install
  # 仮想ディスプレイを作る
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng test --watch=false

notifications:
  email:
    on_failure: change
    on_success: change