sudo: true

language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  # nodeは最新版
  # - node

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install

script:
  - karma start karma.conf.js --single-run